import { Connection, PublicKey } from "@solana/web3.js";
import { Program, AnchorProvider, type Idl } from "@coral-xyz/anchor";
import fs from "node:fs";
import { PROGRAM_ID } from "./constants.js";

/**
 * IMPORTANT — you need to plug in your real IDL here.
 *
 * Point IDL_PATH at the same IDL file your Next.js client already uses to
 * build `Program<TrustExpress>` in useTrustExpress.ts (usually generated by
 * `anchor build` into target/idl/trust_express.json, or wherever the client
 * repo imports it from). This server does NOT redefine the account layout —
 * it decodes accounts through the same IDL the client trusts, so if the
 * program upgrades, you only need to update the IDL file in one place.
 *
 * Without a real IDL, account fetches below will fail at runtime. This is
 * intentional: a hand-rolled byte-offset decoder here would silently drift
 * from the real struct the first time a field is added to the Rust program.
 */
const IDL_PATH = process.env.TRUST_EXPRESS_IDL_PATH ?? "./idl/trust_express.json";

// This used to default to devnet ("https://api.devnet.solana.com") if
// SOLANA_RPC_URL wasn't set. That silent default is what let the mint
// mismatch bug happen invisibly -- the server was reading devnet accounts
// while SUPPORTED_MINTS held mainnet addresses, and nothing errored to flag
// the mismatch. Which network this server talks to changes what "the best
// rate" or "supported tokens" even means, so it must be set explicitly.
function requireRpcUrl(): string {
  const url = process.env.SOLANA_RPC_URL;
  if (!url) {
    throw new Error(
      "SOLANA_RPC_URL is not set. This server previously defaulted to devnet " +
        "silently, which caused real bugs (on-chain data from one network, " +
        "config assumptions from another). Set SOLANA_RPC_URL explicitly to " +
        "whichever network this deployment should read from."
    );
  }
  return url;
}
const RPC_URL = requireRpcUrl();

let cachedProgram: Program | null = null;
let cachedIdl: Idl | null = null;

export function getConnection(): Connection {
  return new Connection(RPC_URL, "confirmed");
}

/** Exposed so helpers.ts can decode on-chain enums (EscrowType, ReservationStatus)
 * straight from the IDL's own type definitions instead of a hardcoded guess. */
export function getIdl(): Idl {
  if (!cachedIdl) {
    // getProgram() populates this as a side effect; call it first if this
    // throws "IDL not loaded yet".
    if (!cachedProgram) {
      throw new Error("getIdl() called before getProgram(). Call getProgram() first.");
    }
  }
  return cachedIdl as Idl;
}

/**
 * Read-only Anchor program client. No wallet/signer — this server never
 * signs anything. That's a phase-1 design constraint, not an oversight:
 * see /areas/trust-vault.md for the phased signing-delegation plan.
 */
export function getProgram(): Program {
  if (cachedProgram) return cachedProgram;

  if (!fs.existsSync(IDL_PATH)) {
    throw new Error(
      `Trust Express IDL not found at ${IDL_PATH}. Set TRUST_EXPRESS_IDL_PATH ` +
        `to the IDL file your client repo already uses (see comment in src/program.ts).`
    );
  }

  const idl: Idl = JSON.parse(fs.readFileSync(IDL_PATH, "utf-8"));
  cachedIdl = idl;

  // Anchor 0.30+ reads the program ID from idl.address, not a constructor
  // arg. Guard against an IDL exported by an older anchor-cli that doesn't
  // carry it, and cross-check it matches the known program ID rather than
  // silently trusting whatever the IDL file says.
  const idlAddress = (idl as any).address;
  if (!idlAddress) {
    throw new Error(
      `IDL at ${IDL_PATH} has no top-level "address" field (Anchor 0.30+ requires it). ` +
        `Re-export the IDL with a current anchor-cli, or add "address": "${PROGRAM_ID.toString()}" manually.`
    );
  }
  if (idlAddress !== PROGRAM_ID.toString()) {
    throw new Error(
      `IDL address (${idlAddress}) does not match the known Trust Express program ID ` +
        `(${PROGRAM_ID.toString()}) in src/constants.ts. Refusing to proceed — check you're ` +
        `pointing at the right IDL/deployment (devnet vs mainnet mismatch is the likely cause).`
    );
  }

  const connection = getConnection();

  // Dummy read-only "wallet" — no real keypair, never signs anything. This
  // server only ever calls .account.<name>.fetch()/.all(), never .methods(),
  // so signTransaction/signAllTransactions are unreachable but must exist
  // to satisfy Anchor's Wallet interface shape.
  const readOnlyWallet = {
    publicKey: PublicKey.default,
    signTransaction: async () => {
      throw new Error("This MCP server is read-only and must never sign transactions.");
    },
    signAllTransactions: async () => {
      throw new Error("This MCP server is read-only and must never sign transactions.");
    },
  };

  const provider = new AnchorProvider(connection, readOnlyWallet as any, {
    commitment: "confirmed",
  });

  cachedProgram = new Program(idl, provider);
  return cachedProgram;
}